blank_issues_enabled: true
contact_links:
  - name: AI Feature Request
    url: https://livepeer-ai-spe.productlane.com/roadmap
    about: "Got a new feature idea for the AI subnet? Check our roadmap and suggest it if it's not there!"
  - name: Go-livepeer Question
    url: https://github.com/livepeer/go-livepeer/discussions
    about: Please ask and answer questions related to the go-livepeer software here.
  - name: Livepeer Question
    url: https://discord.gg/livepeer
    about: "Have a general Livepeer question? Join us in the Livepeer Discord server. We're here to help!"
