# This script is downstream of build-platform and works for both Windows and Linux.

# Don't mess with WORKDIR if you can avoid it, as it's different on Windows/Linux. Use relative
# paths instead.

FROM livepeerci/build-platform:latest

COPY ./install_ffmpeg.sh ./install_ffmpeg.sh
RUN ./install_ffmpeg.sh

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . .
RUN make livepeer livepeer_cli

CMD  ./upload_build.sh
