FROM nvidia/cuda:10.1-base

ENTRYPOINT ["/usr/bin/livepeer"]

COPY --from=livepeerci/build:latest /build/livepeer /usr/bin/livepeer
COPY --from=livepeerci/build:latest /build/livepeer_cli /usr/bin/livepeer_cli
