name: Label issues
on:
  issues:
    types: [opened, reopened]

jobs:
  label_issues:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@master
        with:
          add-labels: "status: triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-if-assigned: false
