name: Label issues

on:
  issues:
    types: [opened, reopened]

jobs:
  label_issues:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit "$ISSUE_URL" --add-label "status: triage"
