name: Label PRs
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
