name: Windows Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: configure git line endings
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
      with:
        # Needed for commands that depend on git tags
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup Msys2 environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
    - name: Prepare mingw64 environment
      shell: msys2 {0}
      run: ./prepare_mingw64.sh
    - name: Build ffmpeg
      shell: msys2 {0}
      run: ./install_ffmpeg.sh
    # For some reason the next step sometimes cannot find protoc
    # - name: Install protoc
    #   uses: arduino/setup-protoc@v1
    # We do not just run `make` because it would also require protoc
    # Due to the issue described above with finding protoc, for now we just specify the individual binaries
    - name: Build binaries
      shell: msys2 {0}
      run: ./ci_env.sh make livepeer livepeer_cli livepeer_bench livepeer_router
    - name: Upload build
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      shell: msys2 {0}
      env: 
        GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      run: ./upload_build.sh
