// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/lp_rpc.proto

package net

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OSInfo_StorageType int32

const (
	OSInfo_DIRECT OSInfo_StorageType = 0
	OSInfo_S3     OSInfo_StorageType = 1
	OSInfo_GOOGLE OSInfo_StorageType = 2
)

var OSInfo_StorageType_name = map[int32]string{
	0: "DIRECT",
	1: "S3",
	2: "GOOGLE",
}

var OSInfo_StorageType_value = map[string]int32{
	"DIRECT": 0,
	"S3":     1,
	"GOOGLE": 2,
}

func (x OSInfo_StorageType) String() string {
	return proto.EnumName(OSInfo_StorageType_name, int32(x))
}

func (OSInfo_StorageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{4, 0}
}

// Desired output format
type VideoProfile_Format int32

const (
	VideoProfile_MPEGTS VideoProfile_Format = 0
	VideoProfile_MP4    VideoProfile_Format = 1
)

var VideoProfile_Format_name = map[int32]string{
	0: "MPEGTS",
	1: "MP4",
}

var VideoProfile_Format_value = map[string]int32{
	"MPEGTS": 0,
	"MP4":    1,
}

func (x VideoProfile_Format) String() string {
	return proto.EnumName(VideoProfile_Format_name, int32(x))
}

func (VideoProfile_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{15, 0}
}

type VideoProfile_Profile int32

const (
	VideoProfile_ENCODER_DEFAULT       VideoProfile_Profile = 0
	VideoProfile_H264_BASELINE         VideoProfile_Profile = 1
	VideoProfile_H264_MAIN             VideoProfile_Profile = 2
	VideoProfile_H264_HIGH             VideoProfile_Profile = 3
	VideoProfile_H264_CONSTRAINED_HIGH VideoProfile_Profile = 4
)

var VideoProfile_Profile_name = map[int32]string{
	0: "ENCODER_DEFAULT",
	1: "H264_BASELINE",
	2: "H264_MAIN",
	3: "H264_HIGH",
	4: "H264_CONSTRAINED_HIGH",
}

var VideoProfile_Profile_value = map[string]int32{
	"ENCODER_DEFAULT":       0,
	"H264_BASELINE":         1,
	"H264_MAIN":             2,
	"H264_HIGH":             3,
	"H264_CONSTRAINED_HIGH": 4,
}

func (x VideoProfile_Profile) String() string {
	return proto.EnumName(VideoProfile_Profile_name, int32(x))
}

func (VideoProfile_Profile) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{15, 1}
}

type VideoProfile_VideoCodec int32

const (
	VideoProfile_H264 VideoProfile_VideoCodec = 0
	VideoProfile_H265 VideoProfile_VideoCodec = 1
	VideoProfile_VP8  VideoProfile_VideoCodec = 2
	VideoProfile_VP9  VideoProfile_VideoCodec = 3
)

var VideoProfile_VideoCodec_name = map[int32]string{
	0: "H264",
	1: "H265",
	2: "VP8",
	3: "VP9",
}

var VideoProfile_VideoCodec_value = map[string]int32{
	"H264": 0,
	"H265": 1,
	"VP8":  2,
	"VP9":  3,
}

func (x VideoProfile_VideoCodec) String() string {
	return proto.EnumName(VideoProfile_VideoCodec_name, int32(x))
}

func (VideoProfile_VideoCodec) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{15, 2}
}

type VideoProfile_ChromaSubsampling int32

const (
	VideoProfile_CHROMA_420 VideoProfile_ChromaSubsampling = 0
	VideoProfile_CHROMA_422 VideoProfile_ChromaSubsampling = 1
	VideoProfile_CHROMA_444 VideoProfile_ChromaSubsampling = 2
)

var VideoProfile_ChromaSubsampling_name = map[int32]string{
	0: "CHROMA_420",
	1: "CHROMA_422",
	2: "CHROMA_444",
}

var VideoProfile_ChromaSubsampling_value = map[string]int32{
	"CHROMA_420": 0,
	"CHROMA_422": 1,
	"CHROMA_444": 2,
}

func (x VideoProfile_ChromaSubsampling) String() string {
	return proto.EnumName(VideoProfile_ChromaSubsampling_name, int32(x))
}

func (VideoProfile_ChromaSubsampling) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{15, 3}
}

type PingPong struct {
	// Implementation defined
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingPong) Reset()         { *m = PingPong{} }
func (m *PingPong) String() string { return proto.CompactTextString(m) }
func (*PingPong) ProtoMessage()    {}
func (*PingPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{0}
}

func (m *PingPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPong.Unmarshal(m, b)
}
func (m *PingPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPong.Marshal(b, m, deterministic)
}
func (m *PingPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPong.Merge(m, src)
}
func (m *PingPong) XXX_Size() int {
	return xxx_messageInfo_PingPong.Size(m)
}
func (m *PingPong) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPong.DiscardUnknown(m)
}

var xxx_messageInfo_PingPong proto.InternalMessageInfo

func (m *PingPong) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// sent by Broadcaster to Orchestrator to terminate the transcoding session and free resources (used for verification sessions)
type EndTranscodingSessionRequest struct {
	// Data for transcoding authentication
	AuthToken            *AuthToken `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EndTranscodingSessionRequest) Reset()         { *m = EndTranscodingSessionRequest{} }
func (m *EndTranscodingSessionRequest) String() string { return proto.CompactTextString(m) }
func (*EndTranscodingSessionRequest) ProtoMessage()    {}
func (*EndTranscodingSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{1}
}

func (m *EndTranscodingSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndTranscodingSessionRequest.Unmarshal(m, b)
}
func (m *EndTranscodingSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndTranscodingSessionRequest.Marshal(b, m, deterministic)
}
func (m *EndTranscodingSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndTranscodingSessionRequest.Merge(m, src)
}
func (m *EndTranscodingSessionRequest) XXX_Size() int {
	return xxx_messageInfo_EndTranscodingSessionRequest.Size(m)
}
func (m *EndTranscodingSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndTranscodingSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndTranscodingSessionRequest proto.InternalMessageInfo

func (m *EndTranscodingSessionRequest) GetAuthToken() *AuthToken {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

type EndTranscodingSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndTranscodingSessionResponse) Reset()         { *m = EndTranscodingSessionResponse{} }
func (m *EndTranscodingSessionResponse) String() string { return proto.CompactTextString(m) }
func (*EndTranscodingSessionResponse) ProtoMessage()    {}
func (*EndTranscodingSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{2}
}

func (m *EndTranscodingSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndTranscodingSessionResponse.Unmarshal(m, b)
}
func (m *EndTranscodingSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndTranscodingSessionResponse.Marshal(b, m, deterministic)
}
func (m *EndTranscodingSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndTranscodingSessionResponse.Merge(m, src)
}
func (m *EndTranscodingSessionResponse) XXX_Size() int {
	return xxx_messageInfo_EndTranscodingSessionResponse.Size(m)
}
func (m *EndTranscodingSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndTranscodingSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndTranscodingSessionResponse proto.InternalMessageInfo

// This request is sent by the broadcaster in `GetTranscoder` to request
// information on which transcoder to use.
type OrchestratorRequest struct {
	// Ethereum address of the broadcaster
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Broadcaster's signature over its address
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrchestratorRequest) Reset()         { *m = OrchestratorRequest{} }
func (m *OrchestratorRequest) String() string { return proto.CompactTextString(m) }
func (*OrchestratorRequest) ProtoMessage()    {}
func (*OrchestratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{3}
}

func (m *OrchestratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrchestratorRequest.Unmarshal(m, b)
}
func (m *OrchestratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrchestratorRequest.Marshal(b, m, deterministic)
}
func (m *OrchestratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrchestratorRequest.Merge(m, src)
}
func (m *OrchestratorRequest) XXX_Size() int {
	return xxx_messageInfo_OrchestratorRequest.Size(m)
}
func (m *OrchestratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrchestratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrchestratorRequest proto.InternalMessageInfo

func (m *OrchestratorRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *OrchestratorRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// OSInfo needed to negotiate storages that will be used.
// It carries info needed to write to the storage.
type OSInfo struct {
	// Storage type: direct, s3, ipfs.
	StorageType          OSInfo_StorageType `protobuf:"varint,1,opt,name=storageType,proto3,enum=net.OSInfo_StorageType" json:"storageType,omitempty"`
	S3Info               *S3OSInfo          `protobuf:"bytes,16,opt,name=s3info,proto3" json:"s3info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OSInfo) Reset()         { *m = OSInfo{} }
func (m *OSInfo) String() string { return proto.CompactTextString(m) }
func (*OSInfo) ProtoMessage()    {}
func (*OSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{4}
}

func (m *OSInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OSInfo.Unmarshal(m, b)
}
func (m *OSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OSInfo.Marshal(b, m, deterministic)
}
func (m *OSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OSInfo.Merge(m, src)
}
func (m *OSInfo) XXX_Size() int {
	return xxx_messageInfo_OSInfo.Size(m)
}
func (m *OSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OSInfo proto.InternalMessageInfo

func (m *OSInfo) GetStorageType() OSInfo_StorageType {
	if m != nil {
		return m.StorageType
	}
	return OSInfo_DIRECT
}

func (m *OSInfo) GetS3Info() *S3OSInfo {
	if m != nil {
		return m.S3Info
	}
	return nil
}

type S3OSInfo struct {
	// Host to use to connect to S3
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Key (prefix) to use when uploading the object.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// POST policy that S3 owner node creates to give write access to other node.
	Policy string `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	// Signature for POST policy.
	Signature string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Needed for POST policy.
	Credential string `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	// Needed for POST policy.
	XAmzDate             string   `protobuf:"bytes,6,opt,name=xAmzDate,proto3" json:"xAmzDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3OSInfo) Reset()         { *m = S3OSInfo{} }
func (m *S3OSInfo) String() string { return proto.CompactTextString(m) }
func (*S3OSInfo) ProtoMessage()    {}
func (*S3OSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{5}
}

func (m *S3OSInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3OSInfo.Unmarshal(m, b)
}
func (m *S3OSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3OSInfo.Marshal(b, m, deterministic)
}
func (m *S3OSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3OSInfo.Merge(m, src)
}
func (m *S3OSInfo) XXX_Size() int {
	return xxx_messageInfo_S3OSInfo.Size(m)
}
func (m *S3OSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S3OSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S3OSInfo proto.InternalMessageInfo

func (m *S3OSInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *S3OSInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *S3OSInfo) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *S3OSInfo) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *S3OSInfo) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

func (m *S3OSInfo) GetXAmzDate() string {
	if m != nil {
		return m.XAmzDate
	}
	return ""
}

// PriceInfo conveys pricing info for transcoding services
type PriceInfo struct {
	// price in wei
	PricePerUnit int64 `protobuf:"varint,1,opt,name=pricePerUnit,proto3" json:"pricePerUnit,omitempty"`
	// Pixels covered in the price
	// Set price to 1 wei and pixelsPerUnit > 1 to have a smaller price granularity per pixel than 1 wei
	PixelsPerUnit        int64    `protobuf:"varint,2,opt,name=pixelsPerUnit,proto3" json:"pixelsPerUnit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceInfo) Reset()         { *m = PriceInfo{} }
func (m *PriceInfo) String() string { return proto.CompactTextString(m) }
func (*PriceInfo) ProtoMessage()    {}
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{6}
}

func (m *PriceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceInfo.Unmarshal(m, b)
}
func (m *PriceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceInfo.Marshal(b, m, deterministic)
}
func (m *PriceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceInfo.Merge(m, src)
}
func (m *PriceInfo) XXX_Size() int {
	return xxx_messageInfo_PriceInfo.Size(m)
}
func (m *PriceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PriceInfo proto.InternalMessageInfo

func (m *PriceInfo) GetPricePerUnit() int64 {
	if m != nil {
		return m.PricePerUnit
	}
	return 0
}

func (m *PriceInfo) GetPixelsPerUnit() int64 {
	if m != nil {
		return m.PixelsPerUnit
	}
	return 0
}

type Capabilities struct {
	// Bit string of supported features - one bit per feature
	Bitstring []uint64 `protobuf:"varint,1,rep,packed,name=bitstring,proto3" json:"bitstring,omitempty"`
	// Bit string of features that are required to be supported
	Mandatories []uint64 `protobuf:"varint,2,rep,packed,name=mandatories,proto3" json:"mandatories,omitempty"`
	// Capacity corresponding to each capability
	Capacities           map[uint32]uint32 `protobuf:"bytes,3,rep,name=capacities,proto3" json:"capacities,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Capabilities) Reset()         { *m = Capabilities{} }
func (m *Capabilities) String() string { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()    {}
func (*Capabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{7}
}

func (m *Capabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities.Unmarshal(m, b)
}
func (m *Capabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities.Marshal(b, m, deterministic)
}
func (m *Capabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities.Merge(m, src)
}
func (m *Capabilities) XXX_Size() int {
	return xxx_messageInfo_Capabilities.Size(m)
}
func (m *Capabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities proto.InternalMessageInfo

func (m *Capabilities) GetBitstring() []uint64 {
	if m != nil {
		return m.Bitstring
	}
	return nil
}

func (m *Capabilities) GetMandatories() []uint64 {
	if m != nil {
		return m.Mandatories
	}
	return nil
}

func (m *Capabilities) GetCapacities() map[uint32]uint32 {
	if m != nil {
		return m.Capacities
	}
	return nil
}

// Non-binary capability constraints, such as supported ranges.
type Capabilities_Constraints struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Capabilities_Constraints) Reset()         { *m = Capabilities_Constraints{} }
func (m *Capabilities_Constraints) String() string { return proto.CompactTextString(m) }
func (*Capabilities_Constraints) ProtoMessage()    {}
func (*Capabilities_Constraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{7, 1}
}

func (m *Capabilities_Constraints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities_Constraints.Unmarshal(m, b)
}
func (m *Capabilities_Constraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities_Constraints.Marshal(b, m, deterministic)
}
func (m *Capabilities_Constraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities_Constraints.Merge(m, src)
}
func (m *Capabilities_Constraints) XXX_Size() int {
	return xxx_messageInfo_Capabilities_Constraints.Size(m)
}
func (m *Capabilities_Constraints) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities_Constraints.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities_Constraints proto.InternalMessageInfo

// The orchestrator sends this in response to `GetOrchestrator`, containing
// miscellaneous data related to the job.
type OrchestratorInfo struct {
	// URI of the transcoder to use for submitting segments.
	Transcoder string `protobuf:"bytes,1,opt,name=transcoder,proto3" json:"transcoder,omitempty"`
	// Parameters for probabilistic micropayment tickets
	TicketParams *TicketParams `protobuf:"bytes,2,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// Price Info containing the price per pixel to transcode
	PriceInfo *PriceInfo `protobuf:"bytes,3,opt,name=price_info,json=priceInfo,proto3" json:"price_info,omitempty"`
	// ETH address that should sign transcoded results
	Address []byte `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// Features and constraints supported by the orchestrator
	Capabilities *Capabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Data for transcoding authentication
	AuthToken *AuthToken `protobuf:"bytes,6,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// Orchestrator returns info about own input object storage, if it wants it to be used.
	Storage              []*OSInfo `protobuf:"bytes,32,rep,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OrchestratorInfo) Reset()         { *m = OrchestratorInfo{} }
func (m *OrchestratorInfo) String() string { return proto.CompactTextString(m) }
func (*OrchestratorInfo) ProtoMessage()    {}
func (*OrchestratorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{8}
}

func (m *OrchestratorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrchestratorInfo.Unmarshal(m, b)
}
func (m *OrchestratorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrchestratorInfo.Marshal(b, m, deterministic)
}
func (m *OrchestratorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrchestratorInfo.Merge(m, src)
}
func (m *OrchestratorInfo) XXX_Size() int {
	return xxx_messageInfo_OrchestratorInfo.Size(m)
}
func (m *OrchestratorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrchestratorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrchestratorInfo proto.InternalMessageInfo

func (m *OrchestratorInfo) GetTranscoder() string {
	if m != nil {
		return m.Transcoder
	}
	return ""
}

func (m *OrchestratorInfo) GetTicketParams() *TicketParams {
	if m != nil {
		return m.TicketParams
	}
	return nil
}

func (m *OrchestratorInfo) GetPriceInfo() *PriceInfo {
	if m != nil {
		return m.PriceInfo
	}
	return nil
}

func (m *OrchestratorInfo) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *OrchestratorInfo) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *OrchestratorInfo) GetAuthToken() *AuthToken {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *OrchestratorInfo) GetStorage() []*OSInfo {
	if m != nil {
		return m.Storage
	}
	return nil
}

// Data for transcoding authentication that is included in the OrchestratorInfo message during discovery
type AuthToken struct {
	// Record used to authenticate for a transcode session
	// Opaque to the receiver
	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// ID of the transcode session that the token is authenticating for
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Timestamp when the token expires
	Expiration           int64    `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{9}
}

func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (m *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(m, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AuthToken) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AuthToken) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

// [EXPERIMENTAL]
// Describes a class that a model is trained to detect
type DetectorClass struct {
	// ID of the class to detect
	ClassId uint32 `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	// Name of the class to detect
	ClassName            string   `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectorClass) Reset()         { *m = DetectorClass{} }
func (m *DetectorClass) String() string { return proto.CompactTextString(m) }
func (*DetectorClass) ProtoMessage()    {}
func (*DetectorClass) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{10}
}

func (m *DetectorClass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectorClass.Unmarshal(m, b)
}
func (m *DetectorClass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectorClass.Marshal(b, m, deterministic)
}
func (m *DetectorClass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectorClass.Merge(m, src)
}
func (m *DetectorClass) XXX_Size() int {
	return xxx_messageInfo_DetectorClass.Size(m)
}
func (m *DetectorClass) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectorClass.DiscardUnknown(m)
}

var xxx_messageInfo_DetectorClass proto.InternalMessageInfo

func (m *DetectorClass) GetClassId() uint32 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

func (m *DetectorClass) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

// [EXPERIMENTAL]
// Describes the scene classification configuration
type SceneClassificationProfile struct {
	// Sample rate of the frames picked by the O for scene detection
	SampleRate uint32 `protobuf:"varint,1,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// List of output classes the model is trained to detect
	Classes              []*DetectorClass `protobuf:"bytes,2,rep,name=classes,proto3" json:"classes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SceneClassificationProfile) Reset()         { *m = SceneClassificationProfile{} }
func (m *SceneClassificationProfile) String() string { return proto.CompactTextString(m) }
func (*SceneClassificationProfile) ProtoMessage()    {}
func (*SceneClassificationProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{11}
}

func (m *SceneClassificationProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneClassificationProfile.Unmarshal(m, b)
}
func (m *SceneClassificationProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneClassificationProfile.Marshal(b, m, deterministic)
}
func (m *SceneClassificationProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneClassificationProfile.Merge(m, src)
}
func (m *SceneClassificationProfile) XXX_Size() int {
	return xxx_messageInfo_SceneClassificationProfile.Size(m)
}
func (m *SceneClassificationProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneClassificationProfile.DiscardUnknown(m)
}

var xxx_messageInfo_SceneClassificationProfile proto.InternalMessageInfo

func (m *SceneClassificationProfile) GetSampleRate() uint32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

func (m *SceneClassificationProfile) GetClasses() []*DetectorClass {
	if m != nil {
		return m.Classes
	}
	return nil
}

// [EXPERIMENTAL]
// Describes the content detection configuration
type DetectorProfile struct {
	// Types that are valid to be assigned to Value:
	//
	//	*DetectorProfile_SceneClassification
	Value                isDetectorProfile_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DetectorProfile) Reset()         { *m = DetectorProfile{} }
func (m *DetectorProfile) String() string { return proto.CompactTextString(m) }
func (*DetectorProfile) ProtoMessage()    {}
func (*DetectorProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{12}
}

func (m *DetectorProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectorProfile.Unmarshal(m, b)
}
func (m *DetectorProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectorProfile.Marshal(b, m, deterministic)
}
func (m *DetectorProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectorProfile.Merge(m, src)
}
func (m *DetectorProfile) XXX_Size() int {
	return xxx_messageInfo_DetectorProfile.Size(m)
}
func (m *DetectorProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectorProfile.DiscardUnknown(m)
}

var xxx_messageInfo_DetectorProfile proto.InternalMessageInfo

type isDetectorProfile_Value interface {
	isDetectorProfile_Value()
}

type DetectorProfile_SceneClassification struct {
	SceneClassification *SceneClassificationProfile `protobuf:"bytes,1,opt,name=scene_classification,json=sceneClassification,proto3,oneof"`
}

func (*DetectorProfile_SceneClassification) isDetectorProfile_Value() {}

func (m *DetectorProfile) GetValue() isDetectorProfile_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DetectorProfile) GetSceneClassification() *SceneClassificationProfile {
	if x, ok := m.GetValue().(*DetectorProfile_SceneClassification); ok {
		return x.SceneClassification
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DetectorProfile) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DetectorProfile_SceneClassification)(nil),
	}
}

// Data included by the broadcaster when submitting a segment for transcoding.
type SegData struct {
	// Manifest ID this segment belongs to
	ManifestId []byte `protobuf:"bytes,1,opt,name=manifestId,proto3" json:"manifestId,omitempty"`
	// Sequence number of the segment to be transcoded
	Seq int64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Hash of the segment data to be transcoded
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	// Transcoding profiles to use
	Profiles []byte `protobuf:"bytes,4,opt,name=profiles,proto3" json:"profiles,omitempty"`
	// Broadcaster signature for the segment. Corresponds to:
	// broadcaster.sign(manifestId | seqNo | dataHash | profiles)
	Sig []byte `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	// Duration of the segment to be transcoded, in milliseconds
	Duration int32 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	// Capabilities used by this segment.
	Capabilities *Capabilities `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Data for transcoding authentication
	AuthToken *AuthToken `protobuf:"bytes,8,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// [EXPERIMENTAL]
	// Detector enabled for this segment
	DetectorEnabled bool `protobuf:"varint,9,opt,name=detector_enabled,json=detectorEnabled,proto3" json:"detector_enabled,omitempty"`
	// Calculate perceptual hash for this segment
	CalcPerceptualHash bool `protobuf:"varint,10,opt,name=calc_perceptual_hash,json=calcPerceptualHash,proto3" json:"calc_perceptual_hash,omitempty"`
	// Broadcaster's preferred storage medium(s)
	// XXX should we include this in a sig somewhere until certs are authenticated?
	Storage []*OSInfo `protobuf:"bytes,32,rep,name=storage,proto3" json:"storage,omitempty"`
	// Transcoding profiles to use. Supersedes `profiles` field
	// Deprecated by `fullProfiles2` but may still be used for mpegts formats
	FullProfiles []*VideoProfile `protobuf:"bytes,33,rep,name=fullProfiles,proto3" json:"fullProfiles,omitempty"`
	// Transcoding profiles to use. Supersedes `fullProfiles` field
	// Deprecated by `fullProfiles3` but may still be used for integer FPS
	FullProfiles2 []*VideoProfile `protobuf:"bytes,34,rep,name=fullProfiles2,proto3" json:"fullProfiles2,omitempty"`
	// Transcoding profiles to use. Supersedes `fullProfiles2` field
	FullProfiles3 []*VideoProfile `protobuf:"bytes,35,rep,name=fullProfiles3,proto3" json:"fullProfiles3,omitempty"`
	// Transcoding parameters specific to this segment
	SegmentParameters *SegParameters `protobuf:"bytes,37,opt,name=segment_parameters,json=segmentParameters,proto3" json:"segment_parameters,omitempty"`
	// Force HW Session Reinit
	ForceSessionReinit bool `protobuf:"varint,38,opt,name=ForceSessionReinit,proto3" json:"ForceSessionReinit,omitempty"`
	// [EXPERIMENTAL]
	// Detector profiles to use
	DetectorProfiles     []*DetectorProfile `protobuf:"bytes,36,rep,name=detector_profiles,json=detectorProfiles,proto3" json:"detector_profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SegData) Reset()         { *m = SegData{} }
func (m *SegData) String() string { return proto.CompactTextString(m) }
func (*SegData) ProtoMessage()    {}
func (*SegData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{13}
}

func (m *SegData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegData.Unmarshal(m, b)
}
func (m *SegData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegData.Marshal(b, m, deterministic)
}
func (m *SegData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegData.Merge(m, src)
}
func (m *SegData) XXX_Size() int {
	return xxx_messageInfo_SegData.Size(m)
}
func (m *SegData) XXX_DiscardUnknown() {
	xxx_messageInfo_SegData.DiscardUnknown(m)
}

var xxx_messageInfo_SegData proto.InternalMessageInfo

func (m *SegData) GetManifestId() []byte {
	if m != nil {
		return m.ManifestId
	}
	return nil
}

func (m *SegData) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SegData) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SegData) GetProfiles() []byte {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *SegData) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SegData) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *SegData) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *SegData) GetAuthToken() *AuthToken {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *SegData) GetDetectorEnabled() bool {
	if m != nil {
		return m.DetectorEnabled
	}
	return false
}

func (m *SegData) GetCalcPerceptualHash() bool {
	if m != nil {
		return m.CalcPerceptualHash
	}
	return false
}

func (m *SegData) GetStorage() []*OSInfo {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *SegData) GetFullProfiles() []*VideoProfile {
	if m != nil {
		return m.FullProfiles
	}
	return nil
}

func (m *SegData) GetFullProfiles2() []*VideoProfile {
	if m != nil {
		return m.FullProfiles2
	}
	return nil
}

func (m *SegData) GetFullProfiles3() []*VideoProfile {
	if m != nil {
		return m.FullProfiles3
	}
	return nil
}

func (m *SegData) GetSegmentParameters() *SegParameters {
	if m != nil {
		return m.SegmentParameters
	}
	return nil
}

func (m *SegData) GetForceSessionReinit() bool {
	if m != nil {
		return m.ForceSessionReinit
	}
	return false
}

func (m *SegData) GetDetectorProfiles() []*DetectorProfile {
	if m != nil {
		return m.DetectorProfiles
	}
	return nil
}

type SegParameters struct {
	// Start timestamp from which to start encoding
	// Milliseconds, from start of the file
	From uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// Skip all frames after that timestamp
	// Milliseconds, from start of the file
	To                   uint64   `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegParameters) Reset()         { *m = SegParameters{} }
func (m *SegParameters) String() string { return proto.CompactTextString(m) }
func (*SegParameters) ProtoMessage()    {}
func (*SegParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{14}
}

func (m *SegParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegParameters.Unmarshal(m, b)
}
func (m *SegParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegParameters.Marshal(b, m, deterministic)
}
func (m *SegParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegParameters.Merge(m, src)
}
func (m *SegParameters) XXX_Size() int {
	return xxx_messageInfo_SegParameters.Size(m)
}
func (m *SegParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_SegParameters.DiscardUnknown(m)
}

var xxx_messageInfo_SegParameters proto.InternalMessageInfo

func (m *SegParameters) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SegParameters) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

type VideoProfile struct {
	// Name of VideoProfile
	Name string `protobuf:"bytes,16,opt,name=name,proto3" json:"name,omitempty"`
	// Width of VideoProfile
	Width int32 `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`
	// Height of VideoProfile
	Height int32 `protobuf:"varint,18,opt,name=height,proto3" json:"height,omitempty"`
	// Bitrate of VideoProfile
	Bitrate int32 `protobuf:"varint,19,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// FPS of VideoProfile
	Fps    uint32              `protobuf:"varint,20,opt,name=fps,proto3" json:"fps,omitempty"`
	Format VideoProfile_Format `protobuf:"varint,21,opt,name=format,proto3,enum=net.VideoProfile_Format" json:"format,omitempty"`
	// FPS Denominator of VideoProfile
	FpsDen uint32 `protobuf:"varint,22,opt,name=fpsDen,proto3" json:"fpsDen,omitempty"`
	// Desired codec profile
	Profile VideoProfile_Profile `protobuf:"varint,23,opt,name=profile,proto3,enum=net.VideoProfile_Profile" json:"profile,omitempty"`
	// GOP interval
	Gop int32 `protobuf:"varint,24,opt,name=gop,proto3" json:"gop,omitempty"`
	// Encoder (video codec)
	Encoder              VideoProfile_VideoCodec        `protobuf:"varint,25,opt,name=encoder,proto3,enum=net.VideoProfile_VideoCodec" json:"encoder,omitempty"`
	ColorDepth           int32                          `protobuf:"varint,26,opt,name=colorDepth,proto3" json:"colorDepth,omitempty"`
	ChromaFormat         VideoProfile_ChromaSubsampling `protobuf:"varint,27,opt,name=chromaFormat,proto3,enum=net.VideoProfile_ChromaSubsampling" json:"chromaFormat,omitempty"`
	Quality              uint32                         `protobuf:"varint,28,opt,name=quality,proto3" json:"quality,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *VideoProfile) Reset()         { *m = VideoProfile{} }
func (m *VideoProfile) String() string { return proto.CompactTextString(m) }
func (*VideoProfile) ProtoMessage()    {}
func (*VideoProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{15}
}

func (m *VideoProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoProfile.Unmarshal(m, b)
}
func (m *VideoProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoProfile.Marshal(b, m, deterministic)
}
func (m *VideoProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoProfile.Merge(m, src)
}
func (m *VideoProfile) XXX_Size() int {
	return xxx_messageInfo_VideoProfile.Size(m)
}
func (m *VideoProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoProfile.DiscardUnknown(m)
}

var xxx_messageInfo_VideoProfile proto.InternalMessageInfo

func (m *VideoProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VideoProfile) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *VideoProfile) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VideoProfile) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *VideoProfile) GetFps() uint32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *VideoProfile) GetFormat() VideoProfile_Format {
	if m != nil {
		return m.Format
	}
	return VideoProfile_MPEGTS
}

func (m *VideoProfile) GetFpsDen() uint32 {
	if m != nil {
		return m.FpsDen
	}
	return 0
}

func (m *VideoProfile) GetProfile() VideoProfile_Profile {
	if m != nil {
		return m.Profile
	}
	return VideoProfile_ENCODER_DEFAULT
}

func (m *VideoProfile) GetGop() int32 {
	if m != nil {
		return m.Gop
	}
	return 0
}

func (m *VideoProfile) GetEncoder() VideoProfile_VideoCodec {
	if m != nil {
		return m.Encoder
	}
	return VideoProfile_H264
}

func (m *VideoProfile) GetColorDepth() int32 {
	if m != nil {
		return m.ColorDepth
	}
	return 0
}

func (m *VideoProfile) GetChromaFormat() VideoProfile_ChromaSubsampling {
	if m != nil {
		return m.ChromaFormat
	}
	return VideoProfile_CHROMA_420
}

func (m *VideoProfile) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

// Individual transcoded segment data.
type TranscodedSegmentData struct {
	// URL where the transcoded data can be downloaded from.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Amount of pixels processed (output pixels)
	Pixels int64 `protobuf:"varint,2,opt,name=pixels,proto3" json:"pixels,omitempty"`
	// URL where the perceptual hash data can be downloaded from (can be empty)
	PerceptualHashUrl    string   `protobuf:"bytes,3,opt,name=perceptual_hash_url,json=perceptualHashUrl,proto3" json:"perceptual_hash_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranscodedSegmentData) Reset()         { *m = TranscodedSegmentData{} }
func (m *TranscodedSegmentData) String() string { return proto.CompactTextString(m) }
func (*TranscodedSegmentData) ProtoMessage()    {}
func (*TranscodedSegmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{16}
}

func (m *TranscodedSegmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodedSegmentData.Unmarshal(m, b)
}
func (m *TranscodedSegmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodedSegmentData.Marshal(b, m, deterministic)
}
func (m *TranscodedSegmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodedSegmentData.Merge(m, src)
}
func (m *TranscodedSegmentData) XXX_Size() int {
	return xxx_messageInfo_TranscodedSegmentData.Size(m)
}
func (m *TranscodedSegmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodedSegmentData.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodedSegmentData proto.InternalMessageInfo

func (m *TranscodedSegmentData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TranscodedSegmentData) GetPixels() int64 {
	if m != nil {
		return m.Pixels
	}
	return 0
}

func (m *TranscodedSegmentData) GetPerceptualHashUrl() string {
	if m != nil {
		return m.PerceptualHashUrl
	}
	return ""
}

// [EXPERIMENTAL]
// Describes scene classification results
type SceneClassificationData struct {
	// Probability that the segment is detected as a particular classID (uint32)
	ClassProbs           map[uint32]float64 `protobuf:"bytes,1,rep,name=class_probs,json=classProbs,proto3" json:"class_probs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SceneClassificationData) Reset()         { *m = SceneClassificationData{} }
func (m *SceneClassificationData) String() string { return proto.CompactTextString(m) }
func (*SceneClassificationData) ProtoMessage()    {}
func (*SceneClassificationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{17}
}

func (m *SceneClassificationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneClassificationData.Unmarshal(m, b)
}
func (m *SceneClassificationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneClassificationData.Marshal(b, m, deterministic)
}
func (m *SceneClassificationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneClassificationData.Merge(m, src)
}
func (m *SceneClassificationData) XXX_Size() int {
	return xxx_messageInfo_SceneClassificationData.Size(m)
}
func (m *SceneClassificationData) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneClassificationData.DiscardUnknown(m)
}

var xxx_messageInfo_SceneClassificationData proto.InternalMessageInfo

func (m *SceneClassificationData) GetClassProbs() map[uint32]float64 {
	if m != nil {
		return m.ClassProbs
	}
	return nil
}

// [EXPERIMENTAL]
// Describes detection results
type DetectData struct {
	// Types that are valid to be assigned to Value:
	//
	//	*DetectData_SceneClassification
	Value                isDetectData_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DetectData) Reset()         { *m = DetectData{} }
func (m *DetectData) String() string { return proto.CompactTextString(m) }
func (*DetectData) ProtoMessage()    {}
func (*DetectData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{18}
}

func (m *DetectData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectData.Unmarshal(m, b)
}
func (m *DetectData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectData.Marshal(b, m, deterministic)
}
func (m *DetectData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectData.Merge(m, src)
}
func (m *DetectData) XXX_Size() int {
	return xxx_messageInfo_DetectData.Size(m)
}
func (m *DetectData) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectData.DiscardUnknown(m)
}

var xxx_messageInfo_DetectData proto.InternalMessageInfo

type isDetectData_Value interface {
	isDetectData_Value()
}

type DetectData_SceneClassification struct {
	SceneClassification *SceneClassificationData `protobuf:"bytes,1,opt,name=scene_classification,json=sceneClassification,proto3,oneof"`
}

func (*DetectData_SceneClassification) isDetectData_Value() {}

func (m *DetectData) GetValue() isDetectData_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DetectData) GetSceneClassification() *SceneClassificationData {
	if x, ok := m.GetValue().(*DetectData_SceneClassification); ok {
		return x.SceneClassification
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DetectData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DetectData_SceneClassification)(nil),
	}
}

// A set of transcoded segments following the profiles specified in the job.
type TranscodeData struct {
	// Transcoded data, in the order specified in the job options
	Segments []*TranscodedSegmentData `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	// Signature of the hash of the concatenated hashes
	Sig []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	// [EXPERIMENTAL]
	// Detection result data in same order as SegData.detector_profiles
	Detections           []*DetectData `protobuf:"bytes,3,rep,name=detections,proto3" json:"detections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TranscodeData) Reset()         { *m = TranscodeData{} }
func (m *TranscodeData) String() string { return proto.CompactTextString(m) }
func (*TranscodeData) ProtoMessage()    {}
func (*TranscodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{19}
}

func (m *TranscodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodeData.Unmarshal(m, b)
}
func (m *TranscodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodeData.Marshal(b, m, deterministic)
}
func (m *TranscodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodeData.Merge(m, src)
}
func (m *TranscodeData) XXX_Size() int {
	return xxx_messageInfo_TranscodeData.Size(m)
}
func (m *TranscodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodeData.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodeData proto.InternalMessageInfo

func (m *TranscodeData) GetSegments() []*TranscodedSegmentData {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *TranscodeData) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *TranscodeData) GetDetections() []*DetectData {
	if m != nil {
		return m.Detections
	}
	return nil
}

// Response that a transcoder sends after transcoding a segment.
type TranscodeResult struct {
	// Sequence number of the transcoded results.
	Seq int64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Result of transcoding can be an error, or successful with more info
	//
	// Types that are valid to be assigned to Result:
	//
	//	*TranscodeResult_Error
	//	*TranscodeResult_Data
	Result isTranscodeResult_Result `protobuf_oneof:"result"`
	// Used to notify a broadcaster of updated orchestrator information
	Info                 *OrchestratorInfo `protobuf:"bytes,16,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TranscodeResult) Reset()         { *m = TranscodeResult{} }
func (m *TranscodeResult) String() string { return proto.CompactTextString(m) }
func (*TranscodeResult) ProtoMessage()    {}
func (*TranscodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{20}
}

func (m *TranscodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodeResult.Unmarshal(m, b)
}
func (m *TranscodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodeResult.Marshal(b, m, deterministic)
}
func (m *TranscodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodeResult.Merge(m, src)
}
func (m *TranscodeResult) XXX_Size() int {
	return xxx_messageInfo_TranscodeResult.Size(m)
}
func (m *TranscodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodeResult proto.InternalMessageInfo

func (m *TranscodeResult) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type isTranscodeResult_Result interface {
	isTranscodeResult_Result()
}

type TranscodeResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type TranscodeResult_Data struct {
	Data *TranscodeData `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

func (*TranscodeResult_Error) isTranscodeResult_Result() {}

func (*TranscodeResult_Data) isTranscodeResult_Result() {}

func (m *TranscodeResult) GetResult() isTranscodeResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *TranscodeResult) GetError() string {
	if x, ok := m.GetResult().(*TranscodeResult_Error); ok {
		return x.Error
	}
	return ""
}

func (m *TranscodeResult) GetData() *TranscodeData {
	if x, ok := m.GetResult().(*TranscodeResult_Data); ok {
		return x.Data
	}
	return nil
}

func (m *TranscodeResult) GetInfo() *OrchestratorInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TranscodeResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TranscodeResult_Error)(nil),
		(*TranscodeResult_Data)(nil),
	}
}

// Sent by the transcoder to register itself to the orchestrator.
type RegisterRequest struct {
	// Shared secret for auth
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Transcoder capacity
	Capacity int64 `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Transcoder capabilities
	Capabilities         *Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{21}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *RegisterRequest) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *RegisterRequest) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

// Sent by the orchestrator to the transcoder
type NotifySegment struct {
	// URL of the segment to transcode.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Configuration for the transcoding job
	SegData *SegData `protobuf:"bytes,3,opt,name=segData,proto3" json:"segData,omitempty"`
	// ID for this particular transcoding task.
	TaskId int64 `protobuf:"varint,16,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// Deprecated by fullProfiles. Set of presets to transcode into.
	// Should be set to an invalid value to induce failures
	Profiles             []byte   `protobuf:"bytes,17,opt,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifySegment) Reset()         { *m = NotifySegment{} }
func (m *NotifySegment) String() string { return proto.CompactTextString(m) }
func (*NotifySegment) ProtoMessage()    {}
func (*NotifySegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{22}
}

func (m *NotifySegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifySegment.Unmarshal(m, b)
}
func (m *NotifySegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifySegment.Marshal(b, m, deterministic)
}
func (m *NotifySegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifySegment.Merge(m, src)
}
func (m *NotifySegment) XXX_Size() int {
	return xxx_messageInfo_NotifySegment.Size(m)
}
func (m *NotifySegment) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifySegment.DiscardUnknown(m)
}

var xxx_messageInfo_NotifySegment proto.InternalMessageInfo

func (m *NotifySegment) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *NotifySegment) GetSegData() *SegData {
	if m != nil {
		return m.SegData
	}
	return nil
}

func (m *NotifySegment) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *NotifySegment) GetProfiles() []byte {
	if m != nil {
		return m.Profiles
	}
	return nil
}

// Required parameters for probabilistic micropayment tickets
type TicketParams struct {
	// ETH address of the recipient
	Recipient []byte `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Pay out (in Wei) to the recipient if the ticket wins
	FaceValue []byte `protobuf:"bytes,2,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Probability that the ticket wins
	WinProb []byte `protobuf:"bytes,3,opt,name=win_prob,json=winProb,proto3" json:"win_prob,omitempty"`
	// 32 byte keccak-256 hash commitment to a random number provided
	// by the recipient
	RecipientRandHash []byte `protobuf:"bytes,4,opt,name=recipient_rand_hash,json=recipientRandHash,proto3" json:"recipient_rand_hash,omitempty"`
	// Value generated by recipient that the recipient can use
	// to derive the random number corresponding to the recipient's hash commitment
	Seed []byte `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`
	// Block number at which the current set of advertised TicketParams is no longer valid
	ExpirationBlock []byte `protobuf:"bytes,6,opt,name=expiration_block,json=expirationBlock,proto3" json:"expiration_block,omitempty"`
	// Expected ticket expiration params
	ExpirationParams     *TicketExpirationParams `protobuf:"bytes,7,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TicketParams) Reset()         { *m = TicketParams{} }
func (m *TicketParams) String() string { return proto.CompactTextString(m) }
func (*TicketParams) ProtoMessage()    {}
func (*TicketParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{23}
}

func (m *TicketParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketParams.Unmarshal(m, b)
}
func (m *TicketParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketParams.Marshal(b, m, deterministic)
}
func (m *TicketParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketParams.Merge(m, src)
}
func (m *TicketParams) XXX_Size() int {
	return xxx_messageInfo_TicketParams.Size(m)
}
func (m *TicketParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketParams proto.InternalMessageInfo

func (m *TicketParams) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *TicketParams) GetFaceValue() []byte {
	if m != nil {
		return m.FaceValue
	}
	return nil
}

func (m *TicketParams) GetWinProb() []byte {
	if m != nil {
		return m.WinProb
	}
	return nil
}

func (m *TicketParams) GetRecipientRandHash() []byte {
	if m != nil {
		return m.RecipientRandHash
	}
	return nil
}

func (m *TicketParams) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *TicketParams) GetExpirationBlock() []byte {
	if m != nil {
		return m.ExpirationBlock
	}
	return nil
}

func (m *TicketParams) GetExpirationParams() *TicketExpirationParams {
	if m != nil {
		return m.ExpirationParams
	}
	return nil
}

// Sender Params (nonces and signatures)
type TicketSenderParams struct {
	// Monotonically increasing counter that makes the ticket
	// unique relative to a particular hash commitment to a recipient's random number
	SenderNonce uint32 `protobuf:"varint,1,opt,name=sender_nonce,json=senderNonce,proto3" json:"sender_nonce,omitempty"`
	// Sender signature over the ticket
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketSenderParams) Reset()         { *m = TicketSenderParams{} }
func (m *TicketSenderParams) String() string { return proto.CompactTextString(m) }
func (*TicketSenderParams) ProtoMessage()    {}
func (*TicketSenderParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{24}
}

func (m *TicketSenderParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketSenderParams.Unmarshal(m, b)
}
func (m *TicketSenderParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketSenderParams.Marshal(b, m, deterministic)
}
func (m *TicketSenderParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketSenderParams.Merge(m, src)
}
func (m *TicketSenderParams) XXX_Size() int {
	return xxx_messageInfo_TicketSenderParams.Size(m)
}
func (m *TicketSenderParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketSenderParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketSenderParams proto.InternalMessageInfo

func (m *TicketSenderParams) GetSenderNonce() uint32 {
	if m != nil {
		return m.SenderNonce
	}
	return 0
}

func (m *TicketSenderParams) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// Ticket params for expiration related validation
type TicketExpirationParams struct {
	// Round during which tickets are created
	CreationRound int64 `protobuf:"varint,1,opt,name=creation_round,json=creationRound,proto3" json:"creation_round,omitempty"`
	// Block hash associated with creation_round
	CreationRoundBlockHash []byte   `protobuf:"bytes,2,opt,name=creation_round_block_hash,json=creationRoundBlockHash,proto3" json:"creation_round_block_hash,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *TicketExpirationParams) Reset()         { *m = TicketExpirationParams{} }
func (m *TicketExpirationParams) String() string { return proto.CompactTextString(m) }
func (*TicketExpirationParams) ProtoMessage()    {}
func (*TicketExpirationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{25}
}

func (m *TicketExpirationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketExpirationParams.Unmarshal(m, b)
}
func (m *TicketExpirationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketExpirationParams.Marshal(b, m, deterministic)
}
func (m *TicketExpirationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketExpirationParams.Merge(m, src)
}
func (m *TicketExpirationParams) XXX_Size() int {
	return xxx_messageInfo_TicketExpirationParams.Size(m)
}
func (m *TicketExpirationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketExpirationParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketExpirationParams proto.InternalMessageInfo

func (m *TicketExpirationParams) GetCreationRound() int64 {
	if m != nil {
		return m.CreationRound
	}
	return 0
}

func (m *TicketExpirationParams) GetCreationRoundBlockHash() []byte {
	if m != nil {
		return m.CreationRoundBlockHash
	}
	return nil
}

// Payment for transcoding video segments
// A payment can constitute of multiple tickets
// A broadcaster might need to send multiple tickets to top up his credit with an Orchestrator
type Payment struct {
	// Probabilistic micropayment ticket parameters
	// These remain the same even when sending multiple tickets
	TicketParams *TicketParams `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// ETH address of the sender
	Sender []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Ticket params for expiration related validation
	ExpirationParams   *TicketExpirationParams `protobuf:"bytes,3,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	TicketSenderParams []*TicketSenderParams   `protobuf:"bytes,4,rep,name=ticket_sender_params,json=ticketSenderParams,proto3" json:"ticket_sender_params,omitempty"`
	// O's last known price
	ExpectedPrice        *PriceInfo `protobuf:"bytes,5,opt,name=expected_price,json=expectedPrice,proto3" json:"expected_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{26}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetTicketParams() *TicketParams {
	if m != nil {
		return m.TicketParams
	}
	return nil
}

func (m *Payment) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Payment) GetExpirationParams() *TicketExpirationParams {
	if m != nil {
		return m.ExpirationParams
	}
	return nil
}

func (m *Payment) GetTicketSenderParams() []*TicketSenderParams {
	if m != nil {
		return m.TicketSenderParams
	}
	return nil
}

func (m *Payment) GetExpectedPrice() *PriceInfo {
	if m != nil {
		return m.ExpectedPrice
	}
	return nil
}

func init() {
	proto.RegisterEnum("net.OSInfo_StorageType", OSInfo_StorageType_name, OSInfo_StorageType_value)
	proto.RegisterEnum("net.VideoProfile_Format", VideoProfile_Format_name, VideoProfile_Format_value)
	proto.RegisterEnum("net.VideoProfile_Profile", VideoProfile_Profile_name, VideoProfile_Profile_value)
	proto.RegisterEnum("net.VideoProfile_VideoCodec", VideoProfile_VideoCodec_name, VideoProfile_VideoCodec_value)
	proto.RegisterEnum("net.VideoProfile_ChromaSubsampling", VideoProfile_ChromaSubsampling_name, VideoProfile_ChromaSubsampling_value)
	proto.RegisterType((*PingPong)(nil), "net.PingPong")
	proto.RegisterType((*EndTranscodingSessionRequest)(nil), "net.EndTranscodingSessionRequest")
	proto.RegisterType((*EndTranscodingSessionResponse)(nil), "net.EndTranscodingSessionResponse")
	proto.RegisterType((*OrchestratorRequest)(nil), "net.OrchestratorRequest")
	proto.RegisterType((*OSInfo)(nil), "net.OSInfo")
	proto.RegisterType((*S3OSInfo)(nil), "net.S3OSInfo")
	proto.RegisterType((*PriceInfo)(nil), "net.PriceInfo")
	proto.RegisterType((*Capabilities)(nil), "net.Capabilities")
	proto.RegisterMapType((map[uint32]uint32)(nil), "net.Capabilities.CapacitiesEntry")
	proto.RegisterType((*Capabilities_Constraints)(nil), "net.Capabilities.Constraints")
	proto.RegisterType((*OrchestratorInfo)(nil), "net.OrchestratorInfo")
	proto.RegisterType((*AuthToken)(nil), "net.AuthToken")
	proto.RegisterType((*DetectorClass)(nil), "net.DetectorClass")
	proto.RegisterType((*SceneClassificationProfile)(nil), "net.SceneClassificationProfile")
	proto.RegisterType((*DetectorProfile)(nil), "net.DetectorProfile")
	proto.RegisterType((*SegData)(nil), "net.SegData")
	proto.RegisterType((*SegParameters)(nil), "net.SegParameters")
	proto.RegisterType((*VideoProfile)(nil), "net.VideoProfile")
	proto.RegisterType((*TranscodedSegmentData)(nil), "net.TranscodedSegmentData")
	proto.RegisterType((*SceneClassificationData)(nil), "net.SceneClassificationData")
	proto.RegisterMapType((map[uint32]float64)(nil), "net.SceneClassificationData.ClassProbsEntry")
	proto.RegisterType((*DetectData)(nil), "net.DetectData")
	proto.RegisterType((*TranscodeData)(nil), "net.TranscodeData")
	proto.RegisterType((*TranscodeResult)(nil), "net.TranscodeResult")
	proto.RegisterType((*RegisterRequest)(nil), "net.RegisterRequest")
	proto.RegisterType((*NotifySegment)(nil), "net.NotifySegment")
	proto.RegisterType((*TicketParams)(nil), "net.TicketParams")
	proto.RegisterType((*TicketSenderParams)(nil), "net.TicketSenderParams")
	proto.RegisterType((*TicketExpirationParams)(nil), "net.TicketExpirationParams")
	proto.RegisterType((*Payment)(nil), "net.Payment")
}

func init() {
	proto.RegisterFile("net/lp_rpc.proto", fileDescriptor_034e29c79f9ba827)
}

var fileDescriptor_034e29c79f9ba827 = []byte{
	// 2101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xdd, 0x6e, 0xdb, 0xc8,
	0x15, 0x36, 0x25, 0x59, 0x3f, 0x47, 0x92, 0x4d, 0x4f, 0x1c, 0x87, 0xf1, 0x26, 0x1b, 0x87, 0x9b,
	0x2c, 0xb2, 0xc0, 0xae, 0x37, 0x90, 0x93, 0x74, 0x53, 0xa0, 0x40, 0x15, 0x5b, 0xb1, 0xb5, 0x88,
	0x6d, 0x75, 0xe4, 0xe4, 0xb2, 0x2a, 0x4d, 0x8e, 0x24, 0xd6, 0x14, 0xc9, 0x70, 0x46, 0x4d, 0xbc,
	0xe8, 0x0b, 0xb4, 0x6f, 0xd0, 0xde, 0x14, 0x28, 0x50, 0xf4, 0x35, 0xfa, 0x00, 0x7d, 0x80, 0xde,
	0x15, 0xe8, 0x93, 0x14, 0x73, 0x66, 0x48, 0x91, 0x96, 0xf3, 0x83, 0xbd, 0x9b, 0xf3, 0x33, 0x33,
	0x67, 0xce, 0xdf, 0x7c, 0x33, 0x60, 0x86, 0x4c, 0x7c, 0x1f, 0xc4, 0xa3, 0x24, 0x76, 0x77, 0xe3,
	0x24, 0x12, 0x11, 0x29, 0x87, 0x4c, 0xd8, 0x3b, 0x50, 0x1f, 0xf8, 0xe1, 0x64, 0x10, 0x85, 0x13,
	0xb2, 0x09, 0xab, 0x7f, 0x70, 0x82, 0x39, 0xb3, 0x8c, 0x1d, 0xe3, 0x51, 0x8b, 0x2a, 0xc2, 0x3e,
	0x86, 0x3b, 0xbd, 0xd0, 0x3b, 0x4b, 0x9c, 0x90, 0xbb, 0x91, 0xe7, 0x87, 0x93, 0x21, 0xe3, 0xdc,
	0x8f, 0x42, 0xca, 0xde, 0xce, 0x19, 0x17, 0xe4, 0x3b, 0x00, 0x67, 0x2e, 0xa6, 0x23, 0x11, 0x5d,
	0xb0, 0x10, 0xa7, 0x36, 0x3b, 0x6b, 0xbb, 0x21, 0x13, 0xbb, 0xdd, 0xb9, 0x98, 0x9e, 0x49, 0x2e,
	0x6d, 0x38, 0xe9, 0xd0, 0xbe, 0x07, 0x77, 0x3f, 0xb0, 0x1c, 0x8f, 0xa3, 0x90, 0x33, 0xbb, 0x0b,
	0x37, 0x4e, 0x13, 0x77, 0xca, 0xb8, 0x48, 0x1c, 0x11, 0x25, 0xe9, 0x36, 0x16, 0xd4, 0x1c, 0xcf,
	0x4b, 0x18, 0xe7, 0xda, 0xbc, 0x94, 0x24, 0x26, 0x94, 0xb9, 0x3f, 0xb1, 0x4a, 0xc8, 0x95, 0x43,
	0xfb, 0x2f, 0x06, 0x54, 0x4f, 0x87, 0xfd, 0x70, 0x1c, 0x91, 0xe7, 0xd0, 0xe4, 0x22, 0x4a, 0x9c,
	0x09, 0x3b, 0xbb, 0x8c, 0xd5, 0xc9, 0xd6, 0x3a, 0xb7, 0xd0, 0x3c, 0xa5, 0xb1, 0x3b, 0x5c, 0x88,
	0x69, 0x5e, 0x97, 0x3c, 0x84, 0x2a, 0xdf, 0xf3, 0xc3, 0x71, 0x64, 0x99, 0x78, 0xa8, 0x36, 0xce,
	0x1a, 0xee, 0xa9, 0x79, 0x54, 0x0b, 0xed, 0xef, 0xa0, 0x99, 0x5b, 0x82, 0x00, 0x54, 0x0f, 0xfa,
	0xb4, 0xb7, 0x7f, 0x66, 0xae, 0x90, 0x2a, 0x94, 0x86, 0x7b, 0xa6, 0x21, 0x79, 0x87, 0xa7, 0xa7,
	0x87, 0xaf, 0x7a, 0x66, 0xc9, 0xfe, 0xbb, 0x01, 0xf5, 0x74, 0x0d, 0x42, 0xa0, 0x32, 0x8d, 0xb8,
	0x40, 0xb3, 0x1a, 0x14, 0xc7, 0xf2, 0x38, 0x17, 0xec, 0x12, 0x8f, 0xd3, 0xa0, 0x72, 0x48, 0xb6,
	0xa0, 0x1a, 0x47, 0x81, 0xef, 0x5e, 0x5a, 0x65, 0x64, 0x6a, 0x8a, 0xdc, 0x81, 0x06, 0xf7, 0x27,
	0xa1, 0x23, 0xe6, 0x09, 0xb3, 0x2a, 0x28, 0x5a, 0x30, 0xc8, 0x97, 0x00, 0x6e, 0xc2, 0x3c, 0x16,
	0x0a, 0xdf, 0x09, 0xac, 0x55, 0x14, 0xe7, 0x38, 0x64, 0x1b, 0xea, 0xef, 0xbb, 0xb3, 0x9f, 0x0e,
	0x1c, 0xc1, 0xac, 0x2a, 0x4a, 0x33, 0xda, 0x7e, 0x0d, 0x8d, 0x41, 0xe2, 0xbb, 0x0c, 0x8d, 0xb4,
	0xa1, 0x15, 0x4b, 0x62, 0xc0, 0x92, 0xd7, 0xa1, 0xaf, 0x8c, 0x2d, 0xd3, 0x02, 0x8f, 0x3c, 0x80,
	0x76, 0xec, 0xbf, 0x67, 0x01, 0x4f, 0x95, 0x4a, 0xa8, 0x54, 0x64, 0xda, 0xff, 0x35, 0xa0, 0xb5,
	0xef, 0xc4, 0xce, 0xb9, 0x1f, 0xf8, 0xc2, 0x67, 0x5c, 0x9e, 0xe0, 0xdc, 0x17, 0x5c, 0x24, 0x7e,
	0x38, 0xb1, 0x8c, 0x9d, 0xf2, 0xa3, 0x0a, 0x5d, 0x30, 0xc8, 0x0e, 0x34, 0x67, 0x4e, 0xe8, 0xc9,
	0x2c, 0xf0, 0x19, 0xb7, 0x4a, 0x28, 0xcf, 0xb3, 0x48, 0x17, 0xc0, 0x75, 0x62, 0xc7, 0xc5, 0xd5,
	0xac, 0xf2, 0x4e, 0xf9, 0x51, 0xb3, 0x73, 0x1f, 0xc3, 0x94, 0xdf, 0x06, 0x09, 0xa5, 0xd3, 0x0b,
	0x45, 0x72, 0x49, 0x73, 0x93, 0xb6, 0x7f, 0x05, 0xeb, 0x57, 0xc4, 0x69, 0x04, 0xe4, 0x39, 0xdb,
	0x2a, 0x02, 0x59, 0x65, 0x94, 0x90, 0xa7, 0x88, 0x5f, 0x96, 0x7e, 0x30, 0xb6, 0xdb, 0xd0, 0xdc,
	0x8f, 0x42, 0x99, 0xab, 0x7e, 0x28, 0xb8, 0xfd, 0xaf, 0x12, 0x98, 0xf9, 0xec, 0x45, 0x07, 0x7e,
	0x09, 0x20, 0x74, 0xbe, 0xb3, 0x44, 0xc7, 0x3a, 0xc7, 0x21, 0xcf, 0xa0, 0x2d, 0x7c, 0xf7, 0x82,
	0x89, 0x51, 0xec, 0x24, 0xce, 0x8c, 0xe3, 0x2e, 0xcd, 0xce, 0x06, 0x1e, 0xe4, 0x0c, 0x25, 0x03,
	0x14, 0xd0, 0x96, 0xc8, 0x51, 0xb2, 0xf2, 0x30, 0x08, 0x23, 0x4c, 0xd2, 0x72, 0xae, 0xf2, 0xb2,
	0xe0, 0xd1, 0x46, 0x9c, 0xc5, 0x31, 0x57, 0x41, 0x95, 0x62, 0x05, 0x3d, 0x85, 0x96, 0x9b, 0xf3,
	0x17, 0x26, 0x4b, 0xba, 0x7f, 0xde, 0x91, 0xb4, 0xa0, 0x76, 0xa5, 0xf2, 0xab, 0x9f, 0xa8, 0x7c,
	0xf2, 0x10, 0x6a, 0xba, 0xbc, 0xac, 0x1d, 0x8c, 0x54, 0x33, 0x57, 0x86, 0x34, 0x95, 0xd9, 0xbf,
	0x83, 0x46, 0x36, 0x5d, 0x3a, 0x7e, 0xd1, 0x57, 0x5a, 0x54, 0x11, 0xe4, 0x2e, 0x00, 0x57, 0x5d,
	0x63, 0xe4, 0x7b, 0xba, 0x52, 0x1a, 0x9a, 0xd3, 0xf7, 0xa4, 0xbf, 0xd9, 0xfb, 0xd8, 0x4f, 0x1c,
	0xe1, 0x47, 0x21, 0xfa, 0xa5, 0x4c, 0x73, 0x1c, 0xbb, 0x0f, 0xed, 0x03, 0x26, 0x98, 0x2b, 0xa2,
	0x64, 0x3f, 0x70, 0x38, 0x27, 0xb7, 0xa1, 0xee, 0xca, 0x81, 0x5c, 0x4d, 0x45, 0xbd, 0x86, 0x74,
	0xdf, 0x93, 0x5b, 0x29, 0x51, 0xe8, 0xcc, 0x58, 0xba, 0x15, 0x72, 0x4e, 0x9c, 0x19, 0xb3, 0x2f,
	0x60, 0x7b, 0xe8, 0xb2, 0x90, 0xe1, 0x3a, 0xfe, 0xd8, 0x77, 0x71, 0x87, 0x41, 0x12, 0x8d, 0xfd,
	0x80, 0x91, 0x7b, 0xd0, 0xe4, 0xce, 0x2c, 0x0e, 0xd8, 0x28, 0x91, 0x55, 0xa6, 0x96, 0x06, 0xc5,
	0xa2, 0x8e, 0x60, 0xe4, 0x5b, 0x50, 0x1b, 0xe9, 0xec, 0x6e, 0x76, 0x08, 0xba, 0xa4, 0x60, 0x1d,
	0x4d, 0x55, 0xec, 0x18, 0xd6, 0x53, 0x49, 0xba, 0xc3, 0x19, 0x6c, 0x72, 0xb9, 0xff, 0xc8, 0x2d,
	0x18, 0xa0, 0xdb, 0xf0, 0x3d, 0xd5, 0xb1, 0x3e, 0x68, 0xe0, 0xd1, 0x0a, 0xbd, 0xc1, 0x97, 0xa5,
	0x2f, 0x6a, 0x3a, 0xdd, 0xed, 0xff, 0xad, 0x42, 0x6d, 0xc8, 0x26, 0x07, 0x8e, 0x70, 0xa4, 0x57,
	0x67, 0x4e, 0xe8, 0x8f, 0x19, 0x17, 0x7d, 0x4f, 0xc7, 0x23, 0xc7, 0xc1, 0x36, 0xcc, 0xde, 0xea,
	0xc2, 0x97, 0x43, 0xec, 0x6e, 0x0e, 0x9f, 0x62, 0x04, 0x5a, 0x14, 0xc7, 0xb2, 0xeb, 0xc4, 0x6a,
	0xf3, 0x34, 0x0b, 0x33, 0x3a, 0x6d, 0xe4, 0xab, 0x59, 0x23, 0x97, 0xda, 0xde, 0x5c, 0xc7, 0x51,
	0xe6, 0xd7, 0x2a, 0xcd, 0xe8, 0xa5, 0xa4, 0xad, 0xfd, 0x9c, 0xa4, 0xad, 0x7f, 0x2a, 0x69, 0xbf,
	0x01, 0xd3, 0xd3, 0x3e, 0x1f, 0xb1, 0xd0, 0x39, 0x0f, 0x98, 0x67, 0x35, 0x76, 0x8c, 0x47, 0x75,
	0xba, 0x9e, 0xf2, 0x7b, 0x8a, 0x4d, 0x1e, 0xc3, 0xa6, 0xeb, 0x04, 0xee, 0x28, 0x66, 0x89, 0xcb,
	0x62, 0x31, 0x77, 0x82, 0x11, 0x1e, 0x1f, 0x50, 0x9d, 0x48, 0xd9, 0x20, 0x13, 0x1d, 0x49, 0x67,
	0x7c, 0x5e, 0x45, 0xc8, 0x93, 0x8e, 0xe7, 0x41, 0x30, 0x48, 0xfd, 0x76, 0x1f, 0x75, 0xd5, 0x49,
	0xdf, 0xf8, 0x1e, 0x8b, 0xb4, 0x84, 0x16, 0xd4, 0xc8, 0x2f, 0xa0, 0x9d, 0xa7, 0x3b, 0x96, 0xfd,
	0xa1, 0x79, 0x45, 0xbd, 0xab, 0x13, 0xf7, 0xac, 0xaf, 0x3e, 0x6b, 0xe2, 0x1e, 0xe9, 0x02, 0xe1,
	0x6c, 0x32, 0x63, 0xa1, 0xee, 0x64, 0x4c, 0xb0, 0x84, 0x5b, 0x0f, 0xd1, 0xc7, 0x2a, 0xb3, 0x87,
	0x6c, 0x32, 0xc8, 0x24, 0x74, 0x43, 0x6b, 0x2f, 0x58, 0x64, 0x17, 0xc8, 0xcb, 0x28, 0x71, 0x59,
	0x86, 0x0a, 0x7c, 0x79, 0x9b, 0x7c, 0xad, 0x5c, 0xb8, 0x2c, 0x21, 0x5d, 0xd8, 0xc8, 0xe2, 0x93,
	0x25, 0xd6, 0x03, 0xb4, 0x77, 0xb3, 0x50, 0x4b, 0xa9, 0xc9, 0x59, 0x38, 0x53, 0xb3, 0xed, 0x3d,
	0x68, 0x17, 0xcc, 0x92, 0x79, 0x3b, 0x4e, 0xa2, 0x19, 0xe6, 0x78, 0x85, 0xe2, 0x98, 0xac, 0x41,
	0x49, 0x44, 0x98, 0xdc, 0x15, 0x5a, 0x12, 0x91, 0xfd, 0xef, 0x55, 0x68, 0xe5, 0x5d, 0x21, 0x27,
	0x61, 0x8b, 0x30, 0xd5, 0x55, 0x2e, 0xc7, 0xb2, 0x7b, 0xbd, 0xf3, 0x3d, 0x31, 0xb5, 0x36, 0x30,
	0x77, 0x15, 0x21, 0xaf, 0xf3, 0x29, 0xf3, 0x27, 0x53, 0x61, 0x11, 0x64, 0x6b, 0x4a, 0xf6, 0xe7,
	0x73, 0x5f, 0x60, 0xa7, 0xb8, 0x81, 0x82, 0x94, 0x94, 0x85, 0x31, 0x8e, 0xb9, 0xb5, 0xa9, 0x2e,
	0xa4, 0x71, 0xcc, 0xc9, 0x63, 0xa8, 0x8e, 0xa3, 0x64, 0xe6, 0x08, 0xeb, 0x26, 0x22, 0x1a, 0x6b,
	0x29, 0x36, 0xbb, 0x2f, 0x51, 0x4e, 0xb5, 0x9e, 0xdc, 0x75, 0x1c, 0xf3, 0x03, 0x16, 0x5a, 0x5b,
	0xb8, 0x8c, 0xa6, 0xc8, 0x1e, 0xd4, 0xb4, 0xdf, 0xac, 0x5b, 0xb8, 0xd4, 0xed, 0xe5, 0xa5, 0x52,
	0xdf, 0xa5, 0x9a, 0xd2, 0xa0, 0x49, 0x14, 0x5b, 0x16, 0x9a, 0x29, 0x87, 0xe4, 0x19, 0xd4, 0x58,
	0xa8, 0x2e, 0xb8, 0xdb, 0xb8, 0xcc, 0x9d, 0xe5, 0x65, 0x90, 0xd8, 0x8f, 0x3c, 0xe6, 0xd2, 0x54,
	0x19, 0x51, 0x4a, 0x14, 0x44, 0xc9, 0x01, 0x8b, 0xc5, 0xd4, 0xda, 0xc6, 0x05, 0x73, 0x1c, 0x72,
	0x08, 0x2d, 0x77, 0x9a, 0x44, 0x33, 0x47, 0x1d, 0xc7, 0xfa, 0x02, 0x17, 0xff, 0x6a, 0x79, 0xf1,
	0x7d, 0xd4, 0x1a, 0xce, 0xcf, 0xb1, 0xbd, 0xfa, 0xe1, 0x84, 0x16, 0x26, 0x4a, 0xef, 0xbe, 0x9d,
	0x3b, 0x81, 0x2f, 0x2e, 0xad, 0x3b, 0xaa, 0xc5, 0x6b, 0xd2, 0xbe, 0x0b, 0x55, 0xad, 0x03, 0x50,
	0x3d, 0x1e, 0xf4, 0x0e, 0xcf, 0x86, 0xe6, 0x0a, 0xa9, 0x41, 0xf9, 0x78, 0xf0, 0xc4, 0x34, 0xec,
	0xdf, 0x43, 0x2d, 0x8d, 0xf1, 0x0d, 0x58, 0xef, 0x9d, 0xec, 0x9f, 0x1e, 0xf4, 0xe8, 0xe8, 0xa0,
	0xf7, 0xb2, 0xfb, 0xfa, 0x95, 0x04, 0x79, 0x1b, 0xd0, 0x3e, 0xea, 0x3c, 0x7b, 0x32, 0x7a, 0xd1,
	0x1d, 0xf6, 0x5e, 0xf5, 0x4f, 0x7a, 0xa6, 0x41, 0xda, 0xd0, 0x40, 0xd6, 0x71, 0xb7, 0x7f, 0x62,
	0x96, 0x32, 0xf2, 0xa8, 0x7f, 0x78, 0x64, 0x96, 0xc9, 0x6d, 0xb8, 0x89, 0xe4, 0xfe, 0xe9, 0xc9,
	0xf0, 0x8c, 0x76, 0xfb, 0x27, 0xbd, 0x03, 0x25, 0xaa, 0xd8, 0x1d, 0x80, 0x85, 0x93, 0x48, 0x1d,
	0x2a, 0x52, 0xd1, 0x5c, 0xd1, 0xa3, 0xa7, 0xa6, 0x21, 0xcd, 0x7a, 0x33, 0xf8, 0xc1, 0x2c, 0xa9,
	0xc1, 0x73, 0xb3, 0x6c, 0xef, 0xc3, 0xc6, 0xd2, 0xd9, 0xc9, 0x1a, 0xc0, 0xfe, 0x11, 0x3d, 0x3d,
	0xee, 0x8e, 0x9e, 0x74, 0x1e, 0x9b, 0x2b, 0x05, 0xba, 0x63, 0x1a, 0x79, 0xfa, 0xc9, 0x13, 0xb3,
	0x64, 0xbf, 0x85, 0x9b, 0x29, 0x24, 0x67, 0xde, 0x50, 0x55, 0x25, 0x76, 0x7d, 0x13, 0xca, 0xf3,
	0x24, 0xd0, 0xa0, 0x45, 0x0e, 0x11, 0x8d, 0x22, 0xaa, 0xd3, 0xad, 0x5e, 0x53, 0x64, 0x17, 0x6e,
	0x5c, 0xe9, 0x7c, 0x23, 0x39, 0x53, 0x41, 0xd6, 0x8d, 0xb8, 0xd0, 0xf9, 0x5e, 0x27, 0x81, 0xfd,
	0x4f, 0x03, 0x6e, 0x5d, 0x73, 0x35, 0xe1, 0xae, 0xc7, 0xd0, 0x54, 0xb7, 0x6e, 0x9c, 0x44, 0xe7,
	0x1c, 0x91, 0x61, 0xb3, 0xf3, 0xed, 0x87, 0x6e, 0x33, 0x39, 0x65, 0x17, 0x59, 0x03, 0xa9, 0x9e,
	0x62, 0xbc, 0x8c, 0x81, 0x18, 0xaf, 0x28, 0xfe, 0x14, 0xc6, 0x33, 0x72, 0x18, 0xcf, 0x9e, 0x02,
	0xa8, 0x2e, 0x82, 0xb6, 0xfd, 0xe6, 0xa3, 0x57, 0xee, 0x9d, 0x8f, 0x19, 0xf9, 0xc9, 0xfb, 0xf6,
	0xcf, 0x06, 0xb4, 0xb3, 0x38, 0xe0, 0x6e, 0xcf, 0xa0, 0xae, 0x9b, 0x64, 0xea, 0x86, 0x6d, 0x05,
	0x0b, 0xaf, 0x8b, 0x16, 0xcd, 0x74, 0x97, 0x1f, 0x45, 0xe4, 0x7b, 0x00, 0xd5, 0xfa, 0xfc, 0x28,
	0x4c, 0xb1, 0xf2, 0x7a, 0xae, 0x45, 0xe2, 0x02, 0x39, 0x15, 0xfb, 0xaf, 0x06, 0xac, 0x67, 0xdb,
	0x50, 0xc6, 0xe7, 0x81, 0x48, 0x2f, 0x79, 0x63, 0x71, 0xc9, 0x6f, 0xc1, 0x2a, 0x4b, 0x92, 0x28,
	0x51, 0xd8, 0xe8, 0x68, 0x85, 0x2a, 0x92, 0x3c, 0x82, 0x8a, 0xe7, 0x08, 0x47, 0xc3, 0x52, 0x52,
	0x34, 0x5a, 0x3b, 0x03, 0x35, 0xc8, 0x37, 0x50, 0xc9, 0xbd, 0xb2, 0x6e, 0xaa, 0x2b, 0xf0, 0x0a,
	0x86, 0xa6, 0xa8, 0xf2, 0xa2, 0x0e, 0xd5, 0x04, 0x0d, 0xb1, 0xff, 0x08, 0xeb, 0x94, 0x4d, 0x7c,
	0x2e, 0x58, 0xf6, 0x42, 0xdc, 0x82, 0x2a, 0x67, 0x6e, 0xc2, 0xd2, 0xe7, 0x94, 0xa6, 0x24, 0x88,
	0xd0, 0x78, 0xff, 0x52, 0xa7, 0x6c, 0x46, 0x2f, 0x81, 0x88, 0xf2, 0x67, 0x81, 0x08, 0xfb, 0x4f,
	0x06, 0xb4, 0x4f, 0x22, 0xe1, 0x8f, 0x2f, 0xb5, 0xf7, 0xaf, 0xa9, 0x93, 0xaf, 0xa1, 0xc6, 0x15,
	0x74, 0xd2, 0xab, 0xb6, 0xd2, 0x1b, 0x10, 0x3d, 0x9d, 0x0a, 0xa5, 0xd9, 0xc2, 0xe1, 0x17, 0x7d,
	0x0f, 0x1d, 0x50, 0xa6, 0x9a, 0x2a, 0x20, 0xa5, 0x8d, 0x22, 0x52, 0xfa, 0xb1, 0x52, 0x2f, 0x99,
	0xe5, 0x1f, 0x2b, 0xf5, 0xfb, 0xa6, 0x6d, 0xff, 0xad, 0x04, 0xad, 0xfc, 0x23, 0x41, 0x3e, 0xaa,
	0x12, 0xe6, 0xfa, 0xb1, 0xcf, 0x42, 0xa1, 0x71, 0xda, 0x82, 0x21, 0x01, 0xed, 0xd8, 0x71, 0xd9,
	0x68, 0x91, 0xeb, 0x2d, 0xda, 0x90, 0x9c, 0x37, 0x92, 0x21, 0xa1, 0xf0, 0x3b, 0x3f, 0xc4, 0xba,
	0xd3, 0xb8, 0xad, 0xf6, 0xce, 0x97, 0x78, 0xf1, 0x5c, 0x16, 0x78, 0xb6, 0xcc, 0x28, 0x71, 0x42,
	0x4f, 0xc1, 0x1b, 0x85, 0xe2, 0x36, 0x32, 0x11, 0x75, 0x42, 0x0f, 0xd1, 0x0d, 0x81, 0x0a, 0x67,
	0xcc, 0xd3, 0x78, 0x0e, 0xc7, 0x12, 0x4e, 0x2d, 0x80, 0xf8, 0xe8, 0x3c, 0x88, 0xdc, 0x0b, 0x04,
	0x76, 0x2d, 0xba, 0xbe, 0xe0, 0xbf, 0x90, 0x6c, 0x72, 0x04, 0x1b, 0x39, 0x55, 0xfd, 0x32, 0x52,
	0x20, 0xef, 0x8b, 0xdc, 0xcb, 0xa8, 0x97, 0xe9, 0xe8, 0x37, 0x52, 0x6e, 0x03, 0xc5, 0xb1, 0xfb,
	0x40, 0x94, 0xee, 0x90, 0x85, 0x1e, 0x4b, 0xb4, 0x9b, 0xee, 0x43, 0x8b, 0x23, 0x3d, 0x0a, 0xa3,
	0xd0, 0x4d, 0xd1, 0x79, 0x53, 0xf1, 0x4e, 0x24, 0xeb, 0x9a, 0x9f, 0x85, 0x9f, 0x60, 0xeb, 0xfa,
	0x6d, 0xc9, 0x43, 0x58, 0x73, 0x13, 0xa6, 0x8c, 0x4d, 0xa2, 0x79, 0xe8, 0xe9, 0x22, 0x69, 0xa7,
	0x5c, 0x2a, 0x99, 0xe4, 0x39, 0xdc, 0x2e, 0xaa, 0x29, 0x27, 0x28, 0x57, 0xaa, 0x8d, 0xb6, 0x0a,
	0x33, 0xd0, 0x19, 0xd2, 0x9f, 0xf6, 0x3f, 0x4a, 0x50, 0x1b, 0x38, 0x97, 0x98, 0x6e, 0x4b, 0x4f,
	0x46, 0xe3, 0xf3, 0x9e, 0x8c, 0x58, 0x23, 0xf2, 0x80, 0x7a, 0x2f, 0x4d, 0x5d, 0xef, 0xec, 0xf2,
	0xcf, 0x70, 0x36, 0xe9, 0xc3, 0xa6, 0xb6, 0x4c, 0x7b, 0x57, 0x2f, 0x56, 0xc1, 0x86, 0x73, 0x2b,
	0xb7, 0x58, 0x3e, 0x1a, 0x94, 0x88, 0xe5, 0x08, 0x3d, 0x85, 0x35, 0xf6, 0x3e, 0x66, 0xae, 0x60,
	0xde, 0x08, 0x9f, 0xb1, 0xfa, 0x61, 0x7a, 0xf5, 0x8d, 0xdb, 0x4e, 0xb5, 0x90, 0xd5, 0xf9, 0x8f,
	0x01, 0xad, 0x7c, 0xff, 0x20, 0x2f, 0x60, 0xfd, 0x90, 0x89, 0x02, 0xcb, 0x5a, 0xea, 0x32, 0xba,
	0x8b, 0x6c, 0x5f, 0xdf, 0x7f, 0xc8, 0x6f, 0xe1, 0xe6, 0xb5, 0xdf, 0x56, 0x44, 0x7d, 0x37, 0x7c,
	0xec, 0x87, 0x6c, 0xdb, 0xfe, 0x98, 0x8a, 0xfa, 0xf5, 0x22, 0x0f, 0xa0, 0x32, 0x90, 0x17, 0xb7,
	0xfa, 0x64, 0x4a, 0xbf, 0xe4, 0xb6, 0x8b, 0x64, 0xe7, 0x04, 0xe0, 0x6c, 0xf1, 0x6f, 0xf0, 0x6b,
	0x20, 0x69, 0x0f, 0xcc, 0x71, 0x15, 0xec, 0xbd, 0xd2, 0x1c, 0xb7, 0x55, 0x03, 0x2e, 0xf4, 0xac,
	0xc7, 0xc6, 0x79, 0x15, 0x7f, 0x02, 0xf7, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x85, 0x1e,
	0xcb, 0x1d, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrchestratorClient interface {
	// Called by the broadcaster to request transcoder info from an orchestrator.
	GetOrchestrator(ctx context.Context, in *OrchestratorRequest, opts ...grpc.CallOption) (*OrchestratorInfo, error)
	EndTranscodingSession(ctx context.Context, in *EndTranscodingSessionRequest, opts ...grpc.CallOption) (*EndTranscodingSessionResponse, error)
	Ping(ctx context.Context, in *PingPong, opts ...grpc.CallOption) (*PingPong, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) GetOrchestrator(ctx context.Context, in *OrchestratorRequest, opts ...grpc.CallOption) (*OrchestratorInfo, error) {
	out := new(OrchestratorInfo)
	err := c.cc.Invoke(ctx, "/net.Orchestrator/GetOrchestrator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) EndTranscodingSession(ctx context.Context, in *EndTranscodingSessionRequest, opts ...grpc.CallOption) (*EndTranscodingSessionResponse, error) {
	out := new(EndTranscodingSessionResponse)
	err := c.cc.Invoke(ctx, "/net.Orchestrator/EndTranscodingSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) Ping(ctx context.Context, in *PingPong, opts ...grpc.CallOption) (*PingPong, error) {
	out := new(PingPong)
	err := c.cc.Invoke(ctx, "/net.Orchestrator/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
type OrchestratorServer interface {
	// Called by the broadcaster to request transcoder info from an orchestrator.
	GetOrchestrator(context.Context, *OrchestratorRequest) (*OrchestratorInfo, error)
	EndTranscodingSession(context.Context, *EndTranscodingSessionRequest) (*EndTranscodingSessionResponse, error)
	Ping(context.Context, *PingPong) (*PingPong, error)
}

// UnimplementedOrchestratorServer can be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (*UnimplementedOrchestratorServer) GetOrchestrator(ctx context.Context, req *OrchestratorRequest) (*OrchestratorInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrchestrator not implemented")
}
func (*UnimplementedOrchestratorServer) EndTranscodingSession(ctx context.Context, req *EndTranscodingSessionRequest) (*EndTranscodingSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTranscodingSession not implemented")
}
func (*UnimplementedOrchestratorServer) Ping(ctx context.Context, req *PingPong) (*PingPong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterOrchestratorServer(s *grpc.Server, srv OrchestratorServer) {
	s.RegisterService(&_Orchestrator_serviceDesc, srv)
}

func _Orchestrator_GetOrchestrator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrchestratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetOrchestrator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.Orchestrator/GetOrchestrator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetOrchestrator(ctx, req.(*OrchestratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_EndTranscodingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndTranscodingSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).EndTranscodingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.Orchestrator/EndTranscodingSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).EndTranscodingSession(ctx, req.(*EndTranscodingSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingPong)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.Orchestrator/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).Ping(ctx, req.(*PingPong))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orchestrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "net.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrchestrator",
			Handler:    _Orchestrator_GetOrchestrator_Handler,
		},
		{
			MethodName: "EndTranscodingSession",
			Handler:    _Orchestrator_EndTranscodingSession_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Orchestrator_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "net/lp_rpc.proto",
}

// TranscoderClient is the client API for Transcoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TranscoderClient interface {
	// Called by the transcoder to register to an orchestrator. The orchestrator
	// notifies registered transcoders of segments as they come in.
	RegisterTranscoder(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (Transcoder_RegisterTranscoderClient, error)
}

type transcoderClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscoderClient(cc grpc.ClientConnInterface) TranscoderClient {
	return &transcoderClient{cc}
}

func (c *transcoderClient) RegisterTranscoder(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (Transcoder_RegisterTranscoderClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Transcoder_serviceDesc.Streams[0], "/net.Transcoder/RegisterTranscoder", opts...)
	if err != nil {
		return nil, err
	}
	x := &transcoderRegisterTranscoderClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Transcoder_RegisterTranscoderClient interface {
	Recv() (*NotifySegment, error)
	grpc.ClientStream
}

type transcoderRegisterTranscoderClient struct {
	grpc.ClientStream
}

func (x *transcoderRegisterTranscoderClient) Recv() (*NotifySegment, error) {
	m := new(NotifySegment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TranscoderServer is the server API for Transcoder service.
type TranscoderServer interface {
	// Called by the transcoder to register to an orchestrator. The orchestrator
	// notifies registered transcoders of segments as they come in.
	RegisterTranscoder(*RegisterRequest, Transcoder_RegisterTranscoderServer) error
}

// UnimplementedTranscoderServer can be embedded to have forward compatible implementations.
type UnimplementedTranscoderServer struct {
}

func (*UnimplementedTranscoderServer) RegisterTranscoder(req *RegisterRequest, srv Transcoder_RegisterTranscoderServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterTranscoder not implemented")
}

func RegisterTranscoderServer(s *grpc.Server, srv TranscoderServer) {
	s.RegisterService(&_Transcoder_serviceDesc, srv)
}

func _Transcoder_RegisterTranscoder_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TranscoderServer).RegisterTranscoder(m, &transcoderRegisterTranscoderServer{stream})
}

type Transcoder_RegisterTranscoderServer interface {
	Send(*NotifySegment) error
	grpc.ServerStream
}

type transcoderRegisterTranscoderServer struct {
	grpc.ServerStream
}

func (x *transcoderRegisterTranscoderServer) Send(m *NotifySegment) error {
	return x.ServerStream.SendMsg(m)
}

var _Transcoder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "net.Transcoder",
	HandlerType: (*TranscoderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterTranscoder",
			Handler:       _Transcoder_RegisterTranscoder_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "net/lp_rpc.proto",
}
