// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: net/lp_rpc.proto

package net

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	// Called by the broadcaster to request transcoder info from an orchestrator.
	GetOrchestrator(ctx context.Context, in *OrchestratorRequest, opts ...grpc.CallOption) (*OrchestratorInfo, error)
	EndTranscodingSession(ctx context.Context, in *EndTranscodingSessionRequest, opts ...grpc.CallOption) (*EndTranscodingSessionResponse, error)
	Ping(ctx context.Context, in *PingPong, opts ...grpc.CallOption) (*PingPong, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) GetOrchestrator(ctx context.Context, in *OrchestratorRequest, opts ...grpc.CallOption) (*OrchestratorInfo, error) {
	out := new(OrchestratorInfo)
	err := c.cc.Invoke(ctx, "/net.Orchestrator/GetOrchestrator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) EndTranscodingSession(ctx context.Context, in *EndTranscodingSessionRequest, opts ...grpc.CallOption) (*EndTranscodingSessionResponse, error) {
	out := new(EndTranscodingSessionResponse)
	err := c.cc.Invoke(ctx, "/net.Orchestrator/EndTranscodingSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) Ping(ctx context.Context, in *PingPong, opts ...grpc.CallOption) (*PingPong, error) {
	out := new(PingPong)
	err := c.cc.Invoke(ctx, "/net.Orchestrator/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility
type OrchestratorServer interface {
	// Called by the broadcaster to request transcoder info from an orchestrator.
	GetOrchestrator(context.Context, *OrchestratorRequest) (*OrchestratorInfo, error)
	EndTranscodingSession(context.Context, *EndTranscodingSessionRequest) (*EndTranscodingSessionResponse, error)
	Ping(context.Context, *PingPong) (*PingPong, error)
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (UnimplementedOrchestratorServer) GetOrchestrator(context.Context, *OrchestratorRequest) (*OrchestratorInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrchestrator not implemented")
}
func (UnimplementedOrchestratorServer) EndTranscodingSession(context.Context, *EndTranscodingSessionRequest) (*EndTranscodingSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTranscodingSession not implemented")
}
func (UnimplementedOrchestratorServer) Ping(context.Context, *PingPong) (*PingPong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_GetOrchestrator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrchestratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetOrchestrator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.Orchestrator/GetOrchestrator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetOrchestrator(ctx, req.(*OrchestratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_EndTranscodingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndTranscodingSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).EndTranscodingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.Orchestrator/EndTranscodingSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).EndTranscodingSession(ctx, req.(*EndTranscodingSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingPong)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.Orchestrator/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).Ping(ctx, req.(*PingPong))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "net.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrchestrator",
			Handler:    _Orchestrator_GetOrchestrator_Handler,
		},
		{
			MethodName: "EndTranscodingSession",
			Handler:    _Orchestrator_EndTranscodingSession_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Orchestrator_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "net/lp_rpc.proto",
}

// TranscoderClient is the client API for Transcoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscoderClient interface {
	// Called by the transcoder to register to an orchestrator. The orchestrator
	// notifies registered transcoders of segments as they come in.
	RegisterTranscoder(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (Transcoder_RegisterTranscoderClient, error)
}

type transcoderClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscoderClient(cc grpc.ClientConnInterface) TranscoderClient {
	return &transcoderClient{cc}
}

func (c *transcoderClient) RegisterTranscoder(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (Transcoder_RegisterTranscoderClient, error) {
	stream, err := c.cc.NewStream(ctx, &Transcoder_ServiceDesc.Streams[0], "/net.Transcoder/RegisterTranscoder", opts...)
	if err != nil {
		return nil, err
	}
	x := &transcoderRegisterTranscoderClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Transcoder_RegisterTranscoderClient interface {
	Recv() (*NotifySegment, error)
	grpc.ClientStream
}

type transcoderRegisterTranscoderClient struct {
	grpc.ClientStream
}

func (x *transcoderRegisterTranscoderClient) Recv() (*NotifySegment, error) {
	m := new(NotifySegment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TranscoderServer is the server API for Transcoder service.
// All implementations must embed UnimplementedTranscoderServer
// for forward compatibility
type TranscoderServer interface {
	// Called by the transcoder to register to an orchestrator. The orchestrator
	// notifies registered transcoders of segments as they come in.
	RegisterTranscoder(*RegisterRequest, Transcoder_RegisterTranscoderServer) error
	mustEmbedUnimplementedTranscoderServer()
}

// UnimplementedTranscoderServer must be embedded to have forward compatible implementations.
type UnimplementedTranscoderServer struct {
}

func (UnimplementedTranscoderServer) RegisterTranscoder(*RegisterRequest, Transcoder_RegisterTranscoderServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterTranscoder not implemented")
}
func (UnimplementedTranscoderServer) mustEmbedUnimplementedTranscoderServer() {}

// UnsafeTranscoderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscoderServer will
// result in compilation errors.
type UnsafeTranscoderServer interface {
	mustEmbedUnimplementedTranscoderServer()
}

func RegisterTranscoderServer(s grpc.ServiceRegistrar, srv TranscoderServer) {
	s.RegisterService(&Transcoder_ServiceDesc, srv)
}

func _Transcoder_RegisterTranscoder_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TranscoderServer).RegisterTranscoder(m, &transcoderRegisterTranscoderServer{stream})
}

type Transcoder_RegisterTranscoderServer interface {
	Send(*NotifySegment) error
	grpc.ServerStream
}

type transcoderRegisterTranscoderServer struct {
	grpc.ServerStream
}

func (x *transcoderRegisterTranscoderServer) Send(m *NotifySegment) error {
	return x.ServerStream.SendMsg(m)
}

// Transcoder_ServiceDesc is the grpc.ServiceDesc for Transcoder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transcoder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "net.Transcoder",
	HandlerType: (*TranscoderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterTranscoder",
			Handler:       _Transcoder_RegisterTranscoder_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "net/lp_rpc.proto",
}
